name = input("What is yur name ? ")
job = input("what job do you wanna aply for ? ")
time = input("How much time woud you take for obtaining this job ? ")
steps = input("what are the steps that you need to follow in order to get to get this job ? ")
first_Day = input("when would you like to start ? ")
print("Candidatul a raspuns urmatoarelor intrebari : ")
print(name, job, time, steps, first_Day)
